name: Feature / Engineering task
description: Add a capability, gate, or refactor with acceptance criteria.
title: "feat: <short description>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Specs-first. If this touches contracts/protocol, include refs and acceptance.

  - type: textarea
    id: objective
    attributes:
      label: Objective
      placeholder: "One sentence. What changes in behavior?"
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope guardrails
      placeholder: |
        In-scope:
        - ...
        Out-of-scope:
        - ...
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: Risks / compatibility
      placeholder: |
        Compatibility class: A|B|C
        Risk notes:
        - ...
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: Law/Specs references
      placeholder: |
        deps/yai-specs/...
        docs/...
    validations:
      required: false

  - type: checkboxes
    id: crossrepo
    attributes:
      label: Cross-repo impact
      options:
        - label: This change requires a twin PR in yai-cli
        - label: This change requires a twin PR in yai-specs
        - label: This change is isolated to this repo only
